config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.main_page, name="main"),
]

movies/urls.py
from django.urls import path
from . import views as movie_views

app_name = "movies"

urlpatterns = [
    path("", movie_views.movie_main, name="main"),
    path("<int:pk>/", movie_views.movie_detail, name="detail"),
    path("create-form/", movie_views.movie_create, name="create"),
    path("create-progress/", movie_views.movie_create_progress, name="create_progress"),
]

movies/models.py
from functools import reduce
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from core.models import TimeStampedModel

# Create your models here.


class Movie(TimeStampedModel):
    title = models.CharField(max_length=30)
    plot = models.TextField(null=True)
    genre = models.ForeignKey(
        "categories.MovieCategory",
        on_delete=models.CASCADE,
    )
    year = models.IntegerField(
        null=True,
        validators=[
            MaxValueValidator(2030),
            MinValueValidator(1900),
        ],
    )
    cover_image = models.ImageField(null=True, blank=True)
    actor = models.ManyToManyField(
        "people.Person", blank=True, related_name="movie_actor"
    )
    # ManyToMnay에서 null은 하나마나다`
    director = models.ForeignKey(
        "people.Person",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="movie_director",
    )

    def __str__(self):
        return self.title

    def total_rating(self):
        all_reviews = self.review_set.all()
        sum = reduce(lambda acc, review: acc + review.rating, all_reviews, 0)
        if not len(all_reviews):
            return "No reviews"
        return round(sum / len(all_reviews), 2)

reviews/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from core.models import TimeStampedModel

# Create your models here.


class Review(TimeStampedModel):
    """ rating은 필수로 받도록 프런트앤드 제작을 해야 함 """

    created_by = models.ForeignKey("users.User", on_delete=models.CASCADE)
    text = models.TextField(null=True)
    rating = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(10),
        ],
        null=True,
        # 실제로 null은 받으면 안된다, 프런트엔드에서 required로 만들자
        blank=True,
    )
    movie = models.ForeignKey(
        "movies.Movie", on_delete=models.CASCADE, null=True, blank=True
    )
    book = models.ForeignKey(
        "books.Book", on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return f"{self.created_by} : {self.text}"

movies/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import models as movie_model
from categories.models import MovieCategory
from people.models import Person
from core.custom_package import (
    sorted_cut,
    sort_by_total_rating,
    sorted_by_total_rating_form_review,
)

# Create your views here.


def movie_main(request):
    page = int(request.GET.get("page", 1) or 1)
    # 말 그대로 request를 GET 메소드로 받아낸다 QueryDict으로 가공된것을 넘겨받는다
    # QueryDict.get()을 사용할수 있따 dir(QueryDict)로 본다
    page_size = 20
    page_count = int(movie_model.Movie.objects.count() / page_size) + 1
    limit = page_size * page
    offset = limit - page_size
    movies = sorted_cut(movie_model.Movie, "year", offset, limit)
    set_movies = sort_by_total_rating(movies)
    set_review = [
        sorted_by_total_rating_form_review(movie[1], 5) for movie in set_movies
    ]
    # 가로5 X 세로4 로 배치, Nav는 수직으로 세워서 배치
    return render(
        request,
        "movies/main.html",
        {
            "movie_data": zip(set_movies, set_review),
            "page": page,
            "page_count": page_count,
            "page_range": range(1, page_count + 1),
        },
    )


def movie_detail(request, pk):
    try:
        page = int(request.GET.get("page", 0) or 0)
        # 일단은 리뷰 더보기 기능으로 생각
        model = movie_model.Movie.objects.get(pk=pk)
        total_rating = model.total_rating()
        reviews = model.review_set.all()
        page_size = 20
        main_page_size = 5
        page_count = int(
            (movie_model.Movie.objects.count() - main_page_size) / page_size
        )
        limit = (page * page_size) + main_page_size
        offset = limit - page_size if limit > main_page_size else 0
        review_data = reviews.order_by("-rating")[offset:limit]
        return render(
            request,
            "movies/detail.html",
            {
                "movie": model,
                "total_rating": total_rating,
                "page_count": page_count - 1,
                "page_range": range(page_count),
                "review_data": review_data,
                "page": page,
            },
        )
    except movie_model.Movie.DoesNotExist:
        return redirect(reverse("movies:main"))


def movie_create(request):
    """
    create movie page definition
    """
    movie_categories = MovieCategory.objects.all()
    actores = Person.objects.filter(kind=Person.KIND_ACTOR)
    directores = Person.objects.filter(kind=Person.KIND_DIRECTOR)
    return render(
        request,
        "movies/create_page.html",
        {
            "movie_categories": movie_categories,
            "actores": actores,
            "directores": directores,
        },
    )


def movie_create_progress(request):
    content = dict(request.POST)
    INPUT_title = content.get("title")  # 모두다 LIST타입!!
    INPUT_plot = content.get("plot")
    INPUT_year = content.get("year")
    INPUT_add_actor = content.get("add_actor")
    INPUT_actor = content.get("actor")[1:]
    # form에서 actor의 default로 None하나가 설정되어있다 그것을 빼고 받아온다
    INPUT_director = content.get("director")
    INPUT_genre = content.get("genre")
    # ---------데이터 정리------------
    try:
        directors = Person.objects.filter(kind="director")
        director = directors.get(name=INPUT_director[0])
        genre = MovieCategory.objects.filter(genre=INPUT_genre[0])[0]
        title = INPUT_title[0]
        plot = INPUT_plot[0]
        year = int(INPUT_year[0])
    except (Person.DoesNotExist, ValueError):
        movie_categories = MovieCategory.objects.all()
        actores = Person.objects.filter(kind=Person.KIND_ACTOR)
        directores = Person.objects.filter(kind=Person.KIND_DIRECTOR)
        return render(
            request,
            "movies/create_page.html",
            {
                "movie_categories": movie_categories,
                "actores": actores,
                "directores": directores,
                "error": "True",
            },
        )
    else:
        movie_instanse = movie_model.Movie(
            title=title, plot=plot, genre=genre, year=year, director=director
        )
        movie_instanse.save()
        # Many To Many를 사용하려면 id가 필요하다 그래서 먼저 save()를 통해 자동 생성되게 해준다
        actors_queryset = Person.objects.filter(kind="actor")
        for name in INPUT_actor:
            filterset = actors_queryset.filter(name=name)
            for actor in filterset:
                movie_instanse.actor.add(actor)
        PK = movie_instanse.pk
        print(PK)
        return HttpResponseRedirect(reverse("movies:detail", args=(PK,)))
    # URL을 다룰때 value뺴고 다 str으로 생각해

templates/movies/create_page.html
{% extends 'base.html' %}


{% block title %}

{% endblock title %}


{% block content %}

<form method="POST" action="{% url 'movies:create_progress' %}">
    {% csrf_token %}
    <label for="title">Title</label>
    <input name='title' id="title" type=" text" placeholder="Title">
    <label for="plot">Plot</label>
    <input name='plot' id="plot" type="text" placeholder="Plot">
    <label for="year">Year</label>
    <input name="year" id="year" type="number" min="1900" max="2030" placeholder="Year">
    <label for="actor">Actor</label>
    <input name="add_actor" type="text" placeholder="Add Actor">
    <select name="actor" id="actor" multiple>
        <option value="" selected>Not here</option>
        {% for actor in actores %}
        <option value="{{actor.name}}">{{actor.name}}</option>
        {% endfor %}
    </select>
    <label for="director">Director</label>
    <select name="director" id="director">
        <option value="" selected>Not here</option>
        {% for director in directores %}
        <option value="{{director.name}}">{{director.name}}</option>
        {% endfor %}
    </select>
    <label for="genre">Genre</label>
    <select name="genre" id="genre">
        {% for movie_category in movie_categories %}
        {% if movie_category.genre == "other" %}
        <option selected value="{{movie_category.genre}}">{{movie_category.genre}}</option>
        {% else %}
        <option value="{{movie_category.genre}}">{{movie_category.genre}}</option>
        {% endif %}
        {% endfor %}
    </select>
    <button>제출</button>

    {% if error == "True" %}
    <h5>값에 누락이 있기 때문에 저장되지 않았습니다. 다시 시도해주세요</h5>
    {% endif %}


</form>

{% endblock content %}

templates/movies/detail.html
{% extends 'base.html' %}


{% block title %}
영화 상세
{% endblock title %}


{% block content %}
<div> 타이틀: {{movie.title}} </div>
<div> 줄거리: {{movie.plot}}</div>
<div> 장르: {{ movie.genre }} </div>
<div> 년도: {{ movie.year }} </div>
{% for actor in movie.actor.all %}
<div>배우들: {{actor}}</div>
{% endfor %}
<div> 감독: {{ movie.director }} </div>
<div> 총평: {{ total_rating }} </div>
{% for review in review_data %}
<div>리뷰 작성자: {{review.created_by}} </div>
<div>리뷰 내용: {{review.text}} </div>
<div>리뷰에서의 평: {{review.rating}} </div>
{% endfor %}

<div> 추가(더보기) 페이지수 {{ page_count }} </div>
{% for page in page_range %}
{% if page != 0 %}
<div> <a href="?page={{page}}">{{ page }}</a> </div>
{% else %}
<div> <a href="?page={{page}}">Main</a> </div>
{% endif %}
{% endfor %}

{% if page is not 0 %}
<div> <a href="?page={{page|add:-1}}">이전</a> </div>
{% endif %}
{% if not page == page_count %}
<div> <a href="?page={{page|add:1}}">다음</a> </div>
{% endif %}


{% endblock content %}

templates/movies/main.html
{% extends 'base.html' %}


{% block title %}
영화 매인
{% endblock title %}


{% block content %}
<a href=" {% url 'movies:create' %} ">영화 등록하기</a>

{% for movie,reviews in movie_data %}
<h1>영화 제목:{{movie.1}} , 총평:{{movie.0}}</h1>
<a href="{% url 'movies:detail' pk=movie.1.pk %}">자세히보기</a>
{% for review_set in reviews %}
{% for review in review_set %}
<div>
    작성자:{{review.created_by}}
    평점{{review.rating}}
    <p>내용:{{review.text}}</p>
</div>
{% endfor %}
<span>------------------------------</span>
{% endfor %}
{% endfor %}


{% if page != 1 %}
<a href="?page={{page|add:'-1'}}">이전</a>
{% endif %}

{% if page != page_count %}
<a href="?page={{page|add:'1'}}">다음</a>
{% endif %}

{% for page in page_range %}
<a href="?page={{ page }}">{{ page }}</a>
{% endfor %}


{% endblock content %}