books/urls.py
from django.urls import path
from . import views as book_views

app_name = "books"

urlpatterns = [
    path("", book_views.book_main, name="main"),
    path("<int:pk>/", book_views.book_detail, name="detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("admin/", admin.site.urls),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.main_page, name="main"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title> {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'partial/header.html' %}
    {% block content %}{% endblock content %}
</body>

</html>

templates/main.html
{% extends 'base.html' %}

{% block title %}
Main page
{% endblock title %}

{% block content %}
<!-- for 문 안에서 -> movie_data[0] = (평점,영화) , movie_data[1] = 그 영화에 대한 리뷰DATA, movie_data[1][0] = 상위3개리뷰 쿼리셋 , movie_data[1][1] = 하위3개리뷰 쿼리셋 -->
<a href="{% url 'movies:main' %}">
    <h1>영화</h1>
</a>
{% for data in movie_data %}
<h2>재목: {{data.0.1.title}}</h2>
<h2>장르: {{data.0.1.genre}}</h2>
<h2>개봉년도: {{data.0.1.year}}</h2>
<h2>감독: {{data.0.1.director}}</h2>
<h2>평균 평점:{{ data.0.0 }}</h2>
<a href=" {% url 'movies:detail' pk=data.0.1.pk %}">자세히 보기</a>
<h3>긍정적인 리뷰 3개 (내림차순 정렬)</h3>
{% for positive_review in data.1.0 %}
<div>작성자 : {{positive_review.created_by}}</div>
<div>평점 : {{positive_review.rating}}</div>
<p>내용 : {{positive_review.text}}</p>
{% endfor %}
<h3>부정적인 리뷰 3개 (오름차순 정렬)</h3>
{% for negative_review in data.1.1 %}
<div>작성자 : {{negative_review.created_by}}</div>
<div>평점 : {{negative_review.rating}}</div>
<p>내용 : {{negative_review.text}}</p>
{% endfor %}
{% endfor %}

<a href="{% url 'books:main' %}">
    <h1>책</h1>
</a>
{% for data in book_data %}
<h2>재목:{{data.0.1.title}}</h2>
<h2>장르:{{data.0.1.genre}}</h2>
<h2>작가:{{data.0.1.writer}}</h2>
<h2>평균 평점:{{ data.0.0 }}</h2>
<a href=" {% url 'books:detail' pk=data.0.1.pk %}">자세히 보기</a>
<h3>긍정적인 리뷰 3개 (내림차순 정렬)</h3>
{% for positive_review in data.1.0 %}
<div>작성자 : {{positive_review.created_by}}</div>
<div>평점 : {{positive_review.rating}}</div>
<p>내용 : {{positive_review.text}}</p>
{% endfor %}
<h3>부정적인 리뷰 3개 (오름차순 정렬)</h3>
{% for negative_review in data.1.1 %}
<div>작성자 : {{negative_review.created_by}}</div>
<div>평점 : {{negative_review.rating}}</div>
<p>내용 : {{negative_review.text}}</p>
{% endfor %}
{% endfor %}

{% endblock content %}